'use strict';
const { company, projects, ideas, timeline, metrics, stories, faqs, sourceNotes } = require('./content');
const { escape: e, link, tag, list, para, section, hero, cta, projectCard, ideaCard, filterBar, steps, faqList, contactForm } = require('./templates');
const buttons = (a, b) => link(a[0], a[1], 'button') + (b ? link(b[0], b[1], 'button button-outline') : '');
const prose = html => '<div class="prose">' + html + '</div>';
const note = html => '<aside class="notice">' + html + '</aside>';
const source = (href, label = 'Read the historical source notes') => {
  const record = sourceNotes.find(item => item.url === href);
  return '<p class="source-note">' + link(record ? '/our-work/sources#' + record.id : href, label) + '</p>';
};
const pair = (a, b) => '<div class="two-col">' + a + b + '</div>';
const panel = (title, text, href, label) => '<article class="editorial-panel"><h3>' + e(title) + '</h3>' + para(text) + (href ? link(href, label, 'text-link') : '') + '</article>';

function makePages(config) {
  const pages = [];
  const add = (path, title, description, body, extra = {}) => pages.push({ path, title, description, body, ...extra });
  const timelineMarkup = '<div class="timeline">' + timeline.map(x => '<article><span class="timeline-date">' + e(x.date) + '</span><div><h3>' + e(x.title) + '</h3>' + para(x.text) + (x.source ? source(x.source, 'Historical source') : '') + '</div></article>').join('') + '</div>';
  const metricsMarkup = '<div class="metrics">' + metrics.map(m => '<div><strong>' + e(m.value) + '</strong><span>' + e(m.label) + '</span></div>').join('') + '</div><p class="source-note">Historical figures reported by StudentSpace. ' + link('/impact', 'Context behind the numbers') + '.</p>';

  add('/', 'Built here. Shared forward.', 'New Mexico helped shape StudentSpace. Explore EdPlan and the education technology we are preparing to share with New Mexico builders.',
    '<section class="home-hero"><div class="wrap hero-grid"><div class="hero-copy"><p class="hero-location"><span aria-hidden="true"></span> Santa Fe, New Mexico · Since 1998</p>' +
    '<h1>Built here.<br>Proven over time.<br><em>Shared forward.</em></h1><p class="lede">New Mexico helped us build a company. Now we’re putting decades of education technology to work for the people building its future.</p>' +
    '<div class="actions">' + buttons(['/build', 'Explore opportunities'], ['/edplan', 'Discover EdPlan.ai']) + '</div><p class="hero-footnote">For students finding a path. For builders creating the next one.</p></div>' +
    '<figure class="hero-art"><img src="/assets/horizon.svg" width="560" height="580" alt="New Mexico horizon with connected pathways extending toward a rising sun." fetchpriority="high"><figcaption><span>Rooted in New Mexico</span><span>Looking ahead, together</span></figcaption></figure></div></section>' +
    '<section class="experience-strip" aria-label="Our experience"><div class="wrap">' + metricsMarkup + '</div></section>' +
    section('One history. Two ways forward.', '<div class="initiative-grid"><article class="initiative student"><div class="initiative-top">' + tag('Available online', 'live') + '<span aria-hidden="true">01 / Students</span></div><div class="initiative-art student-art" aria-hidden="true"><span>Explore</span><i></i><span>Plan</span><i></i><span>Move forward</span></div><h3>Your next step, in view.</h3><p>EdPlan brings career exploration, program discovery and education planning into one place to explore your path.</p>' + link('/edplan', 'Meet EdPlan.ai', 'text-link') + '</article>' +
    '<article class="initiative builder"><div class="initiative-top">' + tag('Taking shape') + '<span aria-hidden="true">02 / Builders</span></div><div class="initiative-art builder-art" aria-hidden="true"><span>&lt; / &gt;</span><span>Ideas + experience</span></div><h3>Our experience. Your next idea.</h3><p>We’re preparing selected technology and product knowledge for New Mexico developers, founders and students to take further.</p>' + link('/build', 'Build with us', 'text-link') + '</article></div>',
    { intro: 'Education opens possibilities. So does sharing what you’ve learned.' }) +
    section('A new chapter, with deep roots.', '<div class="transformation"><article><span>For 25+ years</span><h3>We built education technology.</h3><p>Listening to institutions. Connecting information. Learning what helps people support students.</p></article><article><span>Today</span><h3>We’re putting experience to work.</h3><p>Through a live planning application and a new commitment to share selected technology.</p></article><article><span>What comes next</span><h3>You help write the next chapter.</h3><p>New products, useful ideas and independent businesses are possibilities we hope to enable.</p></article></div>' + link('/mission', 'Why we’re changing', 'text-link'), { className: 'sand-section' }) +
    section('Good ideas deserve another beginning.', '<div class="section-intro-row"><p>Three historical products. Years of real education workflows. A place to start asking what could come next.</p>' + link('/technology', 'Explore the technology library', 'text-link') + '</div><div class="project-grid">' + projects.map(p => projectCard(p)).join('') + '</div>') +
    section('Experience can become opportunity.', '<div class="opportunity-flow"><span>Decades of experience</span><span>Shared technology + knowledge</span><span>New Mexico builders</span><span>New possibilities</span></div><div class="flow-caption"><p>We hope this work can lead to useful products, independent companies and future New Mexico jobs—with knowledge returning to the community.</p>' + link('/impact', 'How we’ll report progress', 'text-link') + '</div>', { className: 'ink-section' }) +
    cta('What will you build next?', 'An idea, a question, a different way of seeing an old problem. We’d like to hear it.'));

  add('/mission', 'Our mission', 'Why StudentSpace is putting its education technology and experience to work for New Mexico students and builders.',
    hero('The place that helped us grow deserves to grow with us.', 'Built in New Mexico. Proven through decades of education technology. Now being shared to help New Mexico build what comes next.', 'Our mission') +
    section('Two commitments. One home.', pair(panel('Help students see a path.', 'EdPlan is an education-planning application supported by StudentSpace. Our direction is to make useful planning tools broadly accessible to students in New Mexico.', '/edplan', 'Explore EdPlan'), panel('Give builders a starting point.', 'We intend to share selected technology, product knowledge and educational software ideas without charge, so New Mexicans can explore what comes next.', '/build', 'Explore the initiative'))) +
    section('A commitment grounded in experience.', prose('<p>Since 1998, StudentSpace has worked on the practical challenges of education: understanding student progress, connecting information and helping institutions offer support. That commercial history matters. It is the experience behind this next chapter.</p><p>StudentSpace remains a for-profit company. Our community commitments are supported by the company; this is not a government program or a claim of official endorsement.</p><p>Sharing technology can create opportunities. It does not guarantee new companies, revenue or jobs. We will report outcomes as evidence becomes available.</p>') + link('/story', 'Read our story', 'text-link'), { className: 'sand-section' }) + cta());

  add('/edplan', 'EdPlan.ai', 'Explore the live EdPlan education-planning application and a separate Northern New Mexico College planning portal.',
    hero('Plan education around where you want to go.', 'Explore possibilities, understand your options and begin building an education plan. EdPlan is available online today.', 'A StudentSpace initiative', buttons([company.edplanUrl, 'Open EdPlan.ai'], ['/contact?intent=edplan', 'Talk about your school'])) +
    section('A clearer way from interest to a plan.', steps([['Explore career paths', 'Start with the areas of work and study that interest you.'], ['Find programs and colleges', 'Explore the program and college-discovery tools in the application.'], ['Create an education plan', 'Use the planning workspace to organize your next steps.'], ['Return to your plans', 'The application includes a saved-plans area; account access may be required.']]) +
      note('<p>Available tools and institutional coverage can vary. Check the application for current requirements and confirm academic decisions with your institution or advisor.</p>')) +
    section('Choose the right starting point.', pair(panel('Explore EdPlan.ai', 'The general EdPlan application offers entry points for career and program exploration, finding a university, creating an education plan and saved plans.', company.edplanUrl, 'Open the general application'), panel('Northern New Mexico College', 'A separate college-specific planning portal provides a Northern New Mexico College context. It is not the general StudentSpace marketing website.', company.collegeUrl, 'Open the NNMC planning portal')), { className: 'sand-section' }) +
    section('Built around real conversations.', '<div class="three-col">' + panel('For students', 'Explore your direction and bring more specific questions to an advising conversation.') + panel('For families', 'Understand the steps involved in an education pathway and support a student’s exploration.') + panel('For educators', 'Discuss where planning tools could fit into the way your school supports students.') + '</div>') +
    section('Growing access, with care.', prose('<p>StudentSpace supports this initiative through its community commitment. Broader access for New Mexico students is the direction we are working toward; it is not a claim of statewide adoption or universal coverage.</p><p>Detailed capabilities, account requirements and application-specific privacy information belong to the live portal. We do not collect academic histories or saved education plans on this website.</p>')) +
    cta('Bring your school into the conversation.', 'Tell us about your students and the planning challenges you’re working on.', '/contact?intent=edplan', 'Contact StudentSpace'));

  add('/build', 'Build With Us', 'Explore the upcoming StudentSpace technology-sharing initiative for New Mexico developers, students and founders.',
    hero('Take experience further. Build what comes next.', 'We’re preparing selected technology, product knowledge and documentation from decades of education work for New Mexico builders.', 'Build With Us', buttons(['/technology', 'Explore the technology'], ['/apply', 'Express your interest'])) +
    section('Find your way in.', '<div class="pathway-grid">' +
      panel('I’m a developer', 'Start with the problems, architecture questions and historical workflows behind the technology.', '/developers', 'The developer pathway') +
      panel('I’m a founder', 'Explore product ideas and the education problems a new business might address.', '/startups', 'The founder pathway') +
      panel('I’m a student', 'Bring a learning goal or project idea. Let us know your connection to New Mexico.', '/apply?intent=build', 'Share your project interest') +
      panel('I’m an educator', 'Help connect the technology conversation to the needs of students and institutions.', '/educators', 'The educator pathway') +
      panel('I represent an organization', 'Discuss a community connection, a shared challenge or a possible collaboration.', '/contact?intent=partner', 'Start a conversation') + '</div>') +
    section('What we intend to share.', pair(prose('<h3>More than code.</h3><p>Useful technology comes with years of decisions: the problem it addressed, the workflow it supported and the lessons from bringing it into institutions.</p>'), list(['Selected source code and prototypes', 'Product designs, architecture and documentation', 'Historical business and implementation knowledge', 'Context from working in education technology'])) +
      note('<p>The release scope is being prepared. No code access, license, individual support allocation or application acceptance is promised by this website. ' + link('/how-it-works', 'Understand the process') + '.</p>'), { className: 'sand-section' }) +
    cta('A starting point for your next idea.', 'Expressing interest helps us understand what New Mexico builders want to work on.'));

  add('/projects', 'Our projects', 'Explore EdPlan.ai, Full Circle Tracking, SchoolView and Assessment of Student Learning: the projects behind StudentSpace’s work in education.',
    hero('Tools for the work of education.', 'From a student’s next step to a clearer picture of an entire institution. Explore the projects behind StudentSpace’s work.', 'Our projects') +
    section('', '<article class="featured-project"><div><p class="section-label">Education planning</p><h2>EdPlan.ai</h2>' + tag('Available online') + '</div><div><p class="lede">A clearer way from interest to a plan.</p><p>Explore careers, programs and colleges, and begin organizing an education pathway. The general application and the Northern New Mexico College portal offer separate starting points.</p><div class="actions">' + buttons(['/edplan', 'Explore EdPlan.ai'], [company.edplanUrl, 'Open the application']) + '</div></div></article>', { className: 'projects-feature-section' }) +
    section('Built from real campus experience.', '<div class="project-overview-grid">' + projects.map(p => '<article class="project-overview-card"><h3>' + e(p.name) + '</h3>' + para(p.history) + link(p.legacyPath, 'View ' + (p.shortName || p.name) + ' details', 'text-link') + '</article>').join('') + '</div>' +
      note('<h3>A foundation for what comes next.</h3><p>These three products form part of our institutional history. Selected technology and documentation are being prepared for New Mexico builders; code access and licensing are not available through these pages yet.</p>' + link('/technology', 'Explore the technology library and release status', 'text-link')), { className: 'sand-section' }) +
    cta('Take the next idea further.', 'Explore the upcoming technology-sharing initiative and tell us what interests you.', '/build', 'Build with us'));

  add('/technology', 'Technology library', 'Explore three historical StudentSpace products and the status of materials being prepared for New Mexico builders.',
    hero('Technology with a history. Possibilities with a future.', 'Explore what the products did, who used them and what a future release could include. Code and licensing are still in preparation.', 'Technology library') +
    section('', '<h2 class="sr-only">Technology projects</h2>' + filterBar(projects.map(p => p.category), 'technology') + '<div class="project-grid">' + projects.map(p => projectCard(p)).join('') + '</div>' +
      note('<h2>Know what is available.</h2><p>These are project descriptions, not downloadable releases. Each approved release will include its own license, documentation and access instructions.</p>' + link('/licensing', 'About licensing', 'text-link'))) + cta());

  for (const p of projects) {
    add('/technology/' + p.slug, p.name + ' project', p.summary,
      hero(p.name, p.summary, p.category, buttons(['/apply?intent=build&project=' + p.slug, 'Express interest'], [p.legacyPath, 'Product history'])) +
      section('', '<div class="detail-grid"><div class="prose"><h2>The problem behind the product</h2>' + para(p.problem) + '<h2>What StudentSpace built</h2>' + para(p.history) +
        '<h2>Who used these workflows</h2>' + list(p.users) + '<h2>Possible next applications</h2>' + list(p.applications) + source(p.source) +
        '</div><aside class="fact-panel"><h2>Project at a glance</h2>' + tag(p.status) + '<dl><dt>Product background</dt><dd>' + e(p.maturity) + '</dd><dt>Code, documentation and demo</dt><dd>Not published for this initiative yet</dd><dt>Release technology stack</dt><dd>To be documented with a release</dd><dt>License</dt><dd>Terms in preparation</dd></dl>' + link('/licensing', 'Read the licensing status', 'text-link') + '</aside></div>') +
      section('What a release could include.', pair(list(p.assets), prose('<h3>Skills and scope</h3>' + para(p.skills) + para(p.scope))) + note('<p>These materials are being considered for release. The final package and permissions will be documented before access begins.</p>'), { className: 'sand-section' }) + cta());
    add(p.legacyPath, p.name + ' — product history', 'Historical context, institutional users and workflows behind StudentSpace’s ' + p.name + '.',
      hero(p.name, p.history, 'Our Work / Historical product') +
      section('Built for the work of education.', pair(prose('<h3>The problem</h3>' + para(p.problem) + '<h3>Who on campus used these workflows</h3>' + list(p.users)), prose('<h3>What could come next</h3>' + para(p.summary) + '<p>Selected materials are being considered for the upcoming technology-sharing initiative. This historical product page does not grant access or software rights.</p>' + link('/technology/' + p.slug, 'Explore the project status', 'text-link'))) + source(p.source)) +
      cta('Take the next idea further.', 'Explore the technology-sharing initiative and tell us what interests you.', '/build', 'Build with us'));
  }

  add('/ideas', 'Ideas worth building', 'Explore education-technology opportunity briefs informed by StudentSpace’s historical work.',
    hero('Decades of problems worth solving.', 'Not every useful idea needs to stay inside the company that first worked on it. Explore education challenges the next generation of New Mexico builders could take further.', 'Idea library') +
    section('', '<h2 class="sr-only">Opportunity briefs</h2>' + filterBar(projects.map(p => p.category), 'ideas') + '<div class="idea-grid">' + ideas.map(ideaCard).join('') + '</div>' +
      note('<p>These briefs describe possibilities, not validated startup offers. They do not promise customers, funding, revenue or access to unreleased materials.</p>')) + cta());
  for (const idea of ideas) {
    const related = projects.find(p => p.slug === idea.project);
    add('/ideas/' + idea.slug, idea.name, idea.summary,
      hero(idea.name, idea.summary, 'Opportunity brief / ' + idea.category) +
      section('', '<div class="detail-grid"><div class="prose">' +
        [['The problem', idea.problem], ['Who experiences it', idea.audience], ['What we learned historically', idea.historicalApproach], ['Why it still matters', idea.whyNow], ['A possible modern approach', idea.approach], ['Where AI might help', idea.ai], ['A possible business direction', idea.business], ['Skills and complexity', idea.complexity]].map(([h, t]) => '<h2>' + e(h) + '</h2>' + para(t)).join('') +
        '</div><aside class="fact-panel"><h2>A place to start</h2>' + tag('Concept to explore') + '<h3>' + e(related.name) + '</h3><p>Selected historical knowledge and materials are being considered for release. Their availability and rights are still being prepared.</p>' +
        link('/technology/' + related.slug, 'Explore the related technology', 'text-link') + '<hr>' + link('/apply?intent=startup&project=' + related.slug, 'Tell us about your idea', 'text-link') + '</aside></div>') + cta());
  }

  const audiencePages = [
    ['/developers', 'For developers', 'Useful problems. Real-world context.', 'Explore the thinking behind education technology before choosing what to build.', 'developer',
      [['Start with the problem', 'Read the project history, understand its users and consider the integrations a new version might require.'], ['Know the release status', 'Repositories, APIs, data models, documentation and starter projects will only be linked when approved for release.'], ['Build with care', 'Use synthetic data in experiments. Do not upload student records, credentials or private institutional information.']],
      '<h2>Developer resources</h2><p>Public repositories, issue trackers, architecture diagrams, contribution guidance, a security policy and a code of conduct are not yet published for this initiative. Approved resources will appear on the relevant project page.</p><p>To raise a security concern, contact support@studentspace.com with a concise description and no sensitive records. We will coordinate any further exchange privately.</p>'],
    ['/startups', 'For New Mexico founders', 'Start with experience, not from zero.', 'Explore established education problems and historical workflows as a starting point for something independently yours.', 'startup',
      [['Choose an opportunity', 'Read an idea brief and identify a problem you want to understand better.'], ['Explore the context', 'Review the related product history and the status of possible code and documentation releases.'], ['Develop your direction', 'Talk to potential users, evaluate the scope and share your interest with StudentSpace.']],
      '<h2>Independent businesses, clear expectations</h2><p>Our intention is to share selected technology and knowledge. Funding, incubation, customers, income and investment are not promised. Any commercial use will depend on the approved license and participation terms.</p>'],
    ['/educators', 'For educators', 'Bring the problems that matter.', 'Your experience with students helps connect technical possibilities to useful work in education.', 'educator',
      [['Explore EdPlan', 'Look at the planning applications and consider the questions your students bring to advising.'], ['Share a workflow', 'Describe an education challenge without including identifiable student information.'], ['Discuss a connection', 'Tell us about your institution or community and what you would like to explore.']],
      '<h2>Experience is part of the design</h2><p>StudentSpace’s products grew from institutional work. This next chapter also needs thoughtful conversations with educators. Contacting us does not establish a partnership or imply that a specific integration is available.</p>']
  ];
  for (const [path, title, headline, description, intent, sequence, body] of audiencePages) {
    add(path, title, description, hero(headline, description, title, buttons(['/technology', 'Explore available information'], ['/contact?intent=' + intent, 'Start a conversation'])) +
      section('A useful starting point.', steps(sequence)) + section('', prose(body), { className: 'sand-section' }) + cta());
  }

  add('/how-it-works', 'How it works', 'Understand the path from exploring StudentSpace technology to future access under approved terms.',
    hero('Explore first. Build with clarity.', 'The sharing program is being prepared. You can explore its direction and express interest today.', 'How it works') +
    section('The intended journey.', steps([['Explore', 'Review historical technologies and opportunity briefs.'], ['Choose', 'Find a problem aligned with your interests or experience.'], ['Understand', 'Review the release scope and license when those are published.'], ['Request access', 'Follow the access process for a released project. Expressions of interest are open now; access is not yet offered here.'], ['Build', 'Develop your work within the rights granted by the applicable terms.'], ['Share progress', 'Optionally tell us what you created, so future outcomes can be documented.']])) +
    cta('You can start with a conversation.', 'Tell us what you are interested in while release details are being prepared.'));

  add('/eligibility', 'Eligibility', 'Current participation status and what New Mexico builders can do while eligibility details are being prepared.',
    hero('Designed with New Mexico in mind.', 'We welcome expressions of interest from people and organizations connected to New Mexico. Detailed participation requirements are still being prepared.', 'Eligibility') +
    section('Who we want to hear from.', list(['Individuals and developers based in New Mexico', 'Students and recent graduates with a New Mexico connection', 'New Mexico founders and early-stage teams', 'Educators and community organizations']) +
      note('<p>These are audiences for a conversation, not finalized acceptance criteria. You do not need to send proof of residency, identity documents or student records through this website.</p>')) +
    section('What is clear today.', prose('<h3>Public information</h3><p>The project descriptions, historical material and idea briefs can be explored now.</p><h3>Technology access</h3><p>There are no code downloads on this website yet. Release-specific permissions, access requirements and any supporting evidence will be explained before access begins.</p><h3>Participation expectations</h3><p>Any obligations will be stated in the applicable terms. An expression of interest does not grant software rights or guarantee acceptance.</p>'), { className: 'sand-section' }) + cta());

  add('/licensing', 'Licensing', 'Release-specific licensing will be published before StudentSpace technology becomes available.',
    hero('Clear terms before you build.', 'Licensing is part of a useful release. Each technology package will state what participants may do before access is offered.', 'Technology access') +
    section('Release terms are in preparation.', prose('<p>We are not publishing a software license through this page. The current project descriptions do not grant permission to download, modify, redistribute, rebrand or commercially use StudentSpace code.</p><p>We use “shared technology” while release terms are being prepared. A geographically focused participation program should not automatically be described as unrestricted open source.</p><p>When a release is ready, its project page will link to the applicable license and describe any access conditions. Questions about intellectual property and commercial use should be resolved against those terms.</p>') +
      '<div class="release-list">' + projects.map(p => '<div><h3>' + e(p.name) + '</h3>' + tag('License not published') + '</div>').join('') + '</div>') + cta('Have a question about a future release?', 'We can record your question while the program details are being prepared.', '/contact?intent=build', 'Ask about technology access'));

  add('/community', 'Community', 'Conversations connecting New Mexico students, educators, developers and founders.',
    hero('More possibilities, through connection.', 'This next chapter is an invitation to New Mexico students, educators, developers and founders to learn from one another.', 'Community') +
    section('Start with what you know.', '<div class="three-col">' + panel('A problem worth solving', 'Bring an education workflow or challenge that would benefit from a clearer approach.', '/contact?intent=educator', 'Share your perspective') +
      panel('A skill to contribute', 'Tell us what you work on and the kinds of projects you are interested in exploring.', '/contact?intent=developer', 'Introduce yourself') +
      panel('A community connection', 'Discuss the people your organization supports and what a useful collaboration could look like.', '/contact?intent=partner', 'Start a conversation') + '</div>') +
    section('We’ll share progress as it happens.', prose('<p>There is no public event calendar, partner directory or community membership program to announce yet. Confirmed activities will be added here as they take shape.</p>'), { className: 'sand-section' }) + cta());

  add('/story', 'Our Story', 'From a Santa Fe beginning in 1998 to a new chapter in education planning and shared technology.',
    hero('Built in New Mexico. Coming full circle.', 'A company’s history is more than a timeline. It is the people, places and practical problems that shape what comes next.', 'Our Story') +
    section('The experience behind the mission.', timelineMarkup) +
    section('The work that brought us here.', '<div class="project-grid">' + projects.map(p => projectCard(p, true)).join('') + '</div>', { className: 'sand-section' }) +
    section('A history of community-minded work.', prose('<p>StudentSpace’s published history describes a willingness to work with smaller institutions and provide tools to under-resourced schools. Historical foundation and CSR activities form part of that context.</p><p>Today’s StudentSpace remains a for-profit company. The technology-sharing initiative is a new company-supported direction, distinct from historical foundation activity.</p>') + source('https://www.studentspace.com/general-8-3', 'Read the historical CSR account')) + cta());

  add('/our-work', 'Our Work', 'Explore StudentSpace’s historical products and institutional work behind its next chapter.',
    hero('Experience worth carrying forward.', 'The products and institutional relationships behind decades of education technology. Preserved as history, and as context for what comes next.', 'Our Work') +
    section('What we built.', '<div class="project-grid">' + projects.map(p => projectCard(p, true)).join('') + '</div>') +
    section('Stories from our institutional work.', '<div class="story-grid">' + stories.map(s => panel(s.name, s.text, '/our-work/' + s.slug, 'Read the historical context')).join('') + '</div>' +
      '<p class="source-note">Historical relationships described in StudentSpace’s published materials. They are not presented as current partnerships or endorsements.</p>', { className: 'sand-section' }) +
    section('A broader history of technical work.', prose('<p>The company also published work in database management, business intelligence and analytics. That service history is preserved here without making it the focus of the new website.</p>') + link('/our-work/services', 'Explore the services history', 'text-link')) + cta());
  for (const s of stories) {
    add('/our-work/' + s.slug, s.name + ' — historical work', s.text,
      hero(s.name, s.text, 'Historical institutional work / ' + s.location) +
      section('Part of the experience behind StudentSpace.', prose('<p>This account is preserved as historical context from StudentSpace’s own published materials. It is not a claim of a current contract, partnership or endorsement.</p><p>Our next chapter draws on experience working with institutions while keeping future program outcomes separate from historical relationships.</p>') + source(s.source) + link('/our-work', 'Return to Our Work', 'text-link')) + cta());
  }
  add('/our-work/services', 'Technical services history', 'Historical context for StudentSpace’s database, business-intelligence and analytics work.',
    hero('Making institutional information useful.', 'StudentSpace’s historical services included database management, business intelligence and business analytics.', 'Our Work / Services history') +
    section('A wider technical foundation.', prose('<p>The company’s legacy site describes database assessment, migration, reporting and analytics services. These capabilities help explain the technical background behind its education products.</p><p>This page preserves that history. It does not advertise a current service package or promise consulting availability.</p>') + source('https://www.studentspace.com/global') + link('/contact', 'Ask about your needs', 'text-link')) + cta());

  add('/our-work/sources', 'Historical source notes', 'Dated company-source notes behind the historical material on the StudentSpace website.',
    hero('Keep the history in context.', 'These notes record the legacy company material consulted on 19 September 2026. They preserve context as the website changes.', 'Historical source notes') +
    section('', prose('<p>These are attributed summaries of company-published material, not an independent audit or a claim of current partnerships. Original addresses are recorded below; after the redesign they may redirect to the new historical pages.</p>') +
      sourceNotes.map(item => '<article class="prose source-record" id="' + item.id + '"><h2>' + e(item.title) + '</h2>' + para(item.note) + '<p class="source-note">Original address: <span>' + e(item.url) + '</span><br>Recorded: 19 September 2026</p></article>').join('')));
  add('/leadership', 'Leadership and accountability', 'Company accountability and contact information while current StudentSpace leadership profiles are being prepared.',
    hero('People, responsibility and a longer view.', 'StudentSpace’s next chapter is a company commitment, grounded in its history of education technology and New Mexico roots.', 'Leadership and accountability') +
    section('A direct line to StudentSpace.', prose('<p>Current leadership profiles will be published when names, roles and biographies have been confirmed. We will not present historical contributors as today’s leadership without verification.</p><p>For questions about the company or the sharing initiative, contact StudentSpace directly.</p>') +
      '<div class="contact-details"><h3>Company office</h3><address>' + e(company.address) + '</address>' + para(company.phone) + link('mailto:' + company.salesEmail, company.salesEmail) + '</div>') + cta());

  add('/impact', 'Impact and transparency', 'The historical evidence behind StudentSpace and how new initiative outcomes will be reported.',
    hero('Experience is our starting point. Evidence will show our progress.', 'We keep historical work separate from the outcomes of this new chapter.', 'Impact and transparency') +
    section('The history behind the numbers.', metricsMarkup + '<div class="prose"><p>The founding year and institution count come from StudentSpace’s published company history. The three products refer to Full Circle Tracking, SchoolView and ASL; they are not three publicly released code packages.</p></div>' + source('https://www.studentspace.com/general-8', 'Company-reported historical background')) +
    section('Impact reporting will begin as projects launch.', prose('<p>We have no new-program participation, company-creation or employment totals to report here yet.</p><p>As evidence becomes available, reporting can include published technology releases, participation, EdPlan use and independently documented projects. Each metric will need a definition, reporting period and source.</p><p>Potential businesses and jobs are intended possibilities, not outcomes we claim to have achieved.</p>'), { className: 'sand-section' }) + cta());

  add('/faq', 'Frequently asked questions', 'Answers about EdPlan, the upcoming technology-sharing program, eligibility, licensing, privacy and participation.',
    hero('A few useful answers.', 'What you can explore today, what is still being prepared and how to start a conversation.', 'Frequently asked questions') +
    [...new Set(faqs.map(f => f.category))].map(category => section(category, faqList(faqs.filter(f => f.category === category)), { className: 'faq-section' })).join('') +
    cta('Still have a question?', 'We’d rather give you a clear answer than leave you guessing.', '/contact', 'Get in touch'));

  for (const apply of [false, true]) {
    add(apply ? '/apply' : '/contact', apply ? 'Express your interest' : 'Contact StudentSpace',
      apply ? 'Tell StudentSpace about your interest in New Mexico technology-building opportunities.' : 'Contact StudentSpace about EdPlan, education technology, community connections or general questions.',
      hero(apply ? 'Every next chapter starts somewhere.' : 'Let’s talk about what comes next.',
        apply ? 'Share your idea or the technology you want to explore. This is an expression of interest, not an application acceptance or a request for immediate code access.' : 'Tell us a little about what you need, and we’ll direct your message to the right conversation.',
        apply ? 'Expressions of interest' : 'Contact') +
      section('', '<div class="form-layout">' + contactForm(apply, config.apiBase) + '<aside class="contact-aside"><h2>Rooted in Santa Fe.</h2><address>' + e(company.address) + '</address>' +
      link('tel:+15054387192', company.phone) + '<hr><h3>Technology-sharing inquiries</h3>' + link('mailto:' + company.givebackEmail, company.givebackEmail) +
      '<h3>General inquiries</h3>' + link('mailto:' + company.salesEmail, company.salesEmail) + '<h3>Support</h3>' + link('mailto:' + company.supportEmail, company.supportEmail) +
      '<div class="aside-note"><p>No payment, student records or identity documents are needed to start a conversation.</p></div></aside></div>'));
  }

  add('/privacy', 'Privacy information', 'How this StudentSpace marketing website handles contact messages, technical requests and links to separate applications.',
    hero('Know where your information goes.', 'A practical explanation of this website’s data handling. The education-planning applications have separate operations and privacy information.', 'Privacy information') +
    section('', prose('<h2>Contact messages</h2><p>When you submit this website’s form, the name, email address, selected intent, message and optional context are sent to the StudentSpace API on Vercel. The backend sends an email through Resend to the StudentSpace advisor inbox.</p><p>This website does not create an application database. That does not mean the message is never stored: email providers and recipient mailboxes process and may retain email. Exact retention periods and handling procedures are being confirmed; contact StudentSpace for details before submitting information if you need them.</p><h2>Technical processing</h2><p>Vercel processes technical request information to operate the site and API. The backend temporarily uses request information for abuse prevention. Application logs are designed to exclude names, email addresses and message contents.</p><h2>Fonts and optional measurement</h2><p>Fonts are requested from Google Fonts. This implementation does not enable an advertising tracker or send form contents to analytics. Any future measurement service should be documented before activation.</p><h2>Separate applications</h2><p>EdPlan and the Northern New Mexico College portal are separate applications. This marketing website does not collect your academic history, account password or saved education plans. Review privacy information within the application you use.</p><h2>Your questions</h2><p>Please send privacy questions or requests to ' + link('mailto:' + company.supportEmail, company.supportEmail) + '. Do not include student records or other sensitive information in the contact form.</p><h2>Notice status</h2><p>This operational notice describes the implemented website. Additional company-approved privacy details will be published as they are confirmed.</p>')));
  add('/terms', 'Website information and terms', 'Information about the purpose of the StudentSpace website and the status of participation and software terms.',
    hero('A clear starting point.', 'This website introduces StudentSpace, its history, live planning applications and an upcoming technology-sharing initiative.', 'Website information') +
    section('', prose('<h2>Information and expressions of interest</h2><p>Project descriptions and opportunity briefs are information for exploration. Submitting a form does not grant access, establish a partnership or guarantee participation.</p><h2>Technology rights</h2><p>No software rights are granted by a product description or idea brief. Approved release-specific terms will be published before code access is offered.</p><h2>Education planning</h2><p>Academic requirements and decisions should be confirmed with the relevant institution or advisor. Separate applications may have their own terms and access requirements.</p><h2>Formal terms</h2><p>Formal participation and release terms are still being prepared. This page does not invent or substitute a software license or participation agreement.</p><h2>Questions</h2><p>Contact ' + link('mailto:' + company.salesEmail, company.salesEmail) + ' for questions about StudentSpace or this website.</p>')));
  add('/accessibility', 'Accessibility', 'Accessibility features, known boundaries and how to report a barrier on the StudentSpace website.',
    hero('A website people can use.', 'We aim for clear language, readable pages and navigation that works with different devices and ways of interacting.', 'Accessibility') +
    section('', prose('<h2>Our approach</h2><p>This website is built with semantic headings, keyboard-accessible navigation, visible focus indicators, labeled form fields and reduced-motion support. Our target is WCAG 2.2 AA; this is not a certification of complete conformance.</p><h2>Using the site</h2><p>Use the skip link to reach the main content. FAQ items use native disclosure controls. Library entries remain readable without JavaScript. Contact-form enhancements require JavaScript; email and telephone alternatives are provided.</p><h2>Report a barrier</h2><p>Email ' + link('mailto:' + company.supportEmail, company.supportEmail) + ' or call ' + link('tel:+15054387192', company.phone) + '. Tell us which page you were using and what prevented you from completing your task. Please avoid sending sensitive information.</p><h2>External applications</h2><p>The EdPlan and college planning portals are separate applications. Accessibility behavior may differ there.</p>')));
  add('/404', 'Page not found', 'This page could not be found. Explore StudentSpace’s mission, technology and education-planning resources.',
    hero('This path stops here.', 'The page may have moved, or the address may not be right. There are plenty of useful places to go next.', '404 / Page not found', buttons(['/', 'Back to home'], ['/technology', 'Explore technology'])), { noindex: true });
  return pages;
}
module.exports = { makePages };
